---
pagetitle: "08:40 / 09:50 - Contributed - C5"
---


<br>


# TBA  {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Chair: TBA

<br>

## Application of statistical techniques to predict the effective temperature of young stars
***
#### *Marco Tarantino, Loredana Prisinzano and Giada Adelfio*

<br>

**Abstract:** One of the current topics of discussion in astrophysical research revolves around the duration of the stellar cluster formation process: some theoretical models postulate formation through a single event (rapid process), others suggest multiple formation events (slow process), implying different ages for stars within the same cluster. A crucial variable for deriving age of young stars is the effective temperature. This study focuses on applying various statistical techniques, such as GLM, SVM, PLSR, Boosting, and Random Forest, to better predict the effective temperature of young stars. The results obtained from the analysis highlight that the Random Forest model outperforms other models in terms of predictive performance.

Click [here]() to view the abstract.

## Topological Attention for Denoising Astronomical Images
***
#### *Riccardo Ceccaroni and Pierpaolo Brutti*

<br>

**Abstract:** Astronomical observations often involve capturing faint signals from celestial objects, such as distant galaxies or dim stars. These signals can be easily overwhelmed by noise, which includes electronic noise, atmospheric interference, and other artifacts. It is then clear that using an effective denoising algorithm is crucial to improve the accuracy of data interpretation by extracting the actual astronomical signals from the noisy background. In this work, we introduce a novel denoising approach based on deep neural networks with pixel attention derived from the topological structure extracted by 0-dimensional Persistent Homology (PH). Our network architecture combines an AutoEncoder (AE) with a Topological Module (TM) that assigns weights to pixels based on PH, providing nuanced attention to the relevant image regions. Our methodology is evaluated against widely used de- noising methods, showcasing its potential for enhancing the quality of astronomical images.

Click [here]() to view the abstract.

## LSTM-based Battery Life Prediction in IoT Systems: a proof of concept
***
#### *Vanessa Verrina, Andrea Vennera and Annarita Renda*

<br>

**Abstract:** Predicting accurately battery life is crucial for applications ranging from electric vehicles and energy storage to emerging technologies in the context of Industry 4.0. The Internet of Things (IoT) has witnessed significant growth, permeating diverse domains. The burgeoning electronics industry has fuelled the demand for portable devices, with IoT devices facing a considerable challenge in ensuring reliable and prolonged battery life. Rechargeable batteries, such as Li-ion systems, are preferred for their high energy density and extended cycle life, aligning with the increasing demand for miniature wireless devices. This work presents a proof-of-concept, employing an optimised Long Short-Term Memory (LSTM) recurrent neural network model to forecast battery life in IoT systems. Utilising publicly available lab datasets and controlled conditions, the results are bench-marked against state-of-the-art models, showcasing the superior performance of the proposed approach. This methodology addresses the critical concern of IoT device battery life, thereby enhancing the reliability and longevity of IoT applications.

Click [here]() to view the abstract.

## Predictive modeling of drivers’ brake reaction time through machine learning methods
***
#### *Alessandro Albano, Giuseppe Salvo and Salvatore Russotto*

<br>

**Abstract:** This paper investigates the task of predicting drivers’ Brake Reaction Time (BRT) using machine learning methods in the context of driving safety. Data is collected using a driving simulator, and interpretability tools such as variable importance and multidimensional partial dependence plots are utilised to interpret the results. The study provides insights into the factors influencing driving safety, with implications for driver training and road safety interventions.

Click [here]() to view the abstract.