---
pagetitle: "08:40 / 09:50 - Contributed - C4"
---


<br>


# TBA  {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Chair: TBA

<br>

## Integrating computational and statistical algorithms in RT-GSCS for spatial survey administration
***
#### *Yuri Calleo, Simone Di Zio and Francesco Pilla*

<br>

**Abstract:** RT-GSCS is a web-based open platform facilitating dynamic spatial surveys
and consensus-building. It supports multiple surveys, where users engage through a
user-friendly map interface, contributing opinions in real-time. RT-GSCS employs a
spatial consensus algorithm inspired by the Delphi method, visually representing
experts’ opinions on the map. The system’s real-time analyses include heat maps,
dynamic clustering, and textual analysis, offering immediate insights. It proves
valuable for decision-making, allowing users to collaboratively identify spatial
information for effective policy implementation. This paper details RT-GSCS’s
administration procedure, consensus algorithm, and spatial support analysis,
highlighting its unique contributions to real-time spatial collaboration systems.

Click [here]() to view the abstract.

## Spatio-temporal analysis of lightning point process data in severe storms
***
#### *Nicoletta D’Angelo, Milind Sharma, Marco Tarantino and Giada Adelfio*

<br>

**Abstract:** This paper deals with the analysis of the 19 May 2013 tornadic supercell in central Oklahoma, exploiting point process theory to estimate the intensity of lightning flashes. We develop a computational strategy to fit spatio-temporal Poisson models, including external covariates, to understand the role of environmental spatio-temporal covariates on the occurrence of such lightning events.

Click [here]() to view the abstract.

## Inferring the dynamics of quasi-reaction systems via non-linear local mean-field approximations
***
#### *Matteo Framba, Veronica Vinciotti and Ernst C. Wit*

<br>

**Abstract:** In modelling stochastic phenomena, parameter estimation of kinetic rates can be challenging, particularly when the time gap between consecutive mea- surements is large. Local linear approximation (LLA) approaches account for the stochasticity in the system but fail to capture the non-linear nature of the underlying process. At the mean level, the dynamics of the system can be described by a system of ordinary differential equations (ODEs), which have an explicit solution only for simple unitary systems. Making use of this, we propose an approximate solution for generic quasi-reaction systems. The explicit ODEs solutions obtained for each time point are used in a non-linear regression framework for conducting inference and prediction for the next time point. The performance of our algorithm is compared to the LLA approach using a simulation study. We show that there is an improvement in the kinetic rate estimation, particularly for data observed at large time intervals.

Click [here]() to view the abstract.

## Investigating hotel consumers’ purchase intention on web analytics data through PLS-SEM
***
#### *Giuseppina Lo Mascolo, Chiara di Maria, Marcello Chiodi and Arabella Mocciaro Li Destri*

<br>

**Abstract:** In an era of rapid technological advancement, the hospitality industry has
witnessed a significant shift towards online booking platforms. This shift necessitates
an exploration of psychological and behavioural factors influencing online purchase
intention. This research investigates the relationships between trust, brand orientation,
and engagement attitude in hotel consumers' online purchase intention. Utilizing
Partial Least Square Structural Equation Modelling (PLS-SEM) on web analytics
data, the study offers a comprehensive analysis of factors influencing consumers'
decision-making in online hotel bookings. The findings enhance understanding of
consumer behaviour in the digital hospitality industry, with implications for
operations, strategy, and management.

Click [here]() to view the abstract.