---
pagetitle: "17:50 / 19:00 - Contributed - C3"
---


<br>


# TBA  {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Chair: TBA

<br>

## A comparison of scalable estimation methods for large-scale logistic regression models with crossed random effects
***
#### *Ruggero Bellio and Cristiano Varin*

<br>

**Abstract:** We focus on stochastic multi-factor models for commodity pricing. Specifically, we conduct an empirical analysis where we compare the pioneering approach initially developed by Schwartz (1997), the three-factor model proposed by Hughen (2010) and the four-factor models presented in Yan (2002) and Schone and Spinler (2017). An in-sample and an out-of-sample analyses focusing on futures prices for copper traded on the London Metal Exchange indicate that while the model proposed by Schone and Spinler (2017) demonstrates superior in-sample performance, the three-factor model by Schwartz (1997) and the four-factor model by Yan (2002) exhibit the lowest out-of-sample root mean square errors.

Click [here]() to view the abstract.

## Nonparametric ranking estimation with application to the propensity for Circular Economy of Italian economic sectors
***
#### *Stefano Bonnini, Michela Borghesi and Massimiliano Giacalone*

<br>

**Abstract:** This work concerns an innovative nonparametric method to estimate the ranking of multivariate populations applied to an economic problem. Circular Economy is spreading very rapidly because the idea that a linear production system is no longer sustainable, from an environmental point of view, is taking hold. The main goal of this work is to determine the ranking of Italian economic sectors according to the tendency to implement various Circular Economy activities, in other words on the propensity towards Circular Economy, based on sample data. The dataset is original and it refers to a survey carried out in Italy in 2020.

Click [here]() to view the abstract.

## Impact of the Russian invasion of Ukraine on coal markets: Evidence from an event-study approach
***
#### *Yana Kostiuk, Paola Cerchiello and Arianna Agosto*

<br>

**Abstract:** We study the immediate market response of the coal-related industry to the onset of the Russian full-scale invasion of Ukraine. Our findings, based on a rigorous event study analysis, indicate a significant and negative reaction in the Eu- ropean region on the 21st and 24th of February, followed by an increase in average abnormal returns (AARs) on the first day following the invasion. As for Emerging countries, no results were observed for China, while India registered positive AARs on the second and third day of the war. Over the designated 14-day event period, positive Cumulative Average Abnormal Returns (CAARs) are evident in all examined sub-samples, though statistical significance is observed only within the Titans sub-sample.

Click [here]() to view the abstract.

## Labour market and time series: a forecast approach for European countries from 1995 to 2022
***
#### *Paolo Mariani, Andrea Marletta and Piero Quatto*

<br>

**Abstract:** In statistical literature, many contributions investigated the relation
between macro-economic variables and the employment rates obtained from the
Labour Force Survey. The main aim of the work is to detect the presence of an
economic growth, measured by GDP, followed by a positive dynamic of the
considered employment rates in some EU countries. A three-way data analysis
approach has been proposed to track the evolution of the relationship during time in
each country. An original approach based on the superior influence of the most
recent observations has been used to obtain predictions for the future coordinates of
the trajectories. The proposed method also provided prediction intervals in order to
display a measure of the prediction error.

Click [here]() to view the abstract.