---
pagetitle: "17:50 / 19:00 - Contributed - C2"
---


<br>


# TBA  {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Chair: TBA

<br>

## Analysis of Brain-Body Physiological Rhythm Using Functional Graphical Models
***
#### *Rita Fici, Luigi Augugliaro and Ernst C. Wit*

<br>

**Abstract:** This paper presents an analysis of physiological data derived from a recent investigation on network physiology, adopting the conceptual framework that views the human organism as a complex network of interacting organs. The study explores coordinated interactions among organs using functional conditional Gaussian Graphical Models (fcGGM). Organ functions are modelled as networks with individual regulatory mechanisms, forming a broader system through continuous interactions. The focus of the analysis is on the interactions within and between two subnetworks: brain activity and a composite network comprising the RR interval of the electrocardiographic waveform, respiration amplitude and blood volume pulse.


Click [here]() to view the abstract.

## A comparison of multi-factor stochastic models for commodity prices
***
#### *Luca Vincenzo Ballestra, Christian Tezza and Paolo Foschi*

<br>

**Abstract:** Parameter estimation of generalized linear models with crossed random effects for large-scale settings is hampered by challenging numerical hindrances. This contribution focuses on logistic regression with crossed-random intercepts and it investigates the properties of two estimation methods for which a scalable software implementation exists, namely the all-row-column and penalized quasi- likelihood methods. The results of a simulation study for sparse settings inspired by e-commerce data, with sample sizes up to $10^6$ suggest that the all-row-column method is preferable over penalized quasi-likelihood.

Click [here]() to view the abstract.

## Single-cell Sequencing Data: Critical Analysis and Definition of Statistical Models
***
#### *Antonino Gagliano, Gianluca Sottile, Nicolina Sciaraffa, Claudia Coronnello and Luigi Augugliaro*

<br>

**Abstract:**  In the past decade, advances in single-cell RNA sequencing technologies have radically improved the comprehension of cell biology. Pseudo-time computation has revealed greater heterogeneity in cell differentiation, which is important for the study of various diseases. In this paper we evaluate pseudo-time calculation methodologies and propose statistical models for analyzing the relationship between pseudo-time and gene expression.


Click [here]() to view the abstract.

## Completion of Partially Observed Multivariate Functional Data
***
#### *Marco Borriero, Luigi Augugliaro, Salvatore Latora and Veronica Vinciotti*

<br>

**Abstract:** Functional data often present missing values. These pose challenges when performing functional principal components analysis, since it is not possible to compute the scores from the data. The existing method by Kraus (2015) allows to perform functional data completion in a univariate setting. In this paper, we propose an extension to the multivariate setting and show how statistical dependences between the functional curves aid in the imputation of missing data.

Click [here]() to view the abstract.