---
pagetitle: "17:50 / 19:00 - Contributed - C1"
---


<br>


# TBA  {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Chair: TBA

<br>

## Lesson Learnt in the Data Science Worldview: New Dimension of Digital Divide
***
#### *Rita Lima*

<br>

**Abstract:** In this paper we discuss if it's a great time to be a data scientist entering the job market. The starting point of this discussion is the recent availability of extremely huge datasets (Big Data) in many formats and potentially in real-time, while the new data science techniques constantly being developed, for maximising the value of this data. National Statistical Offices accommodate the widespread needs to shortage qualified human resources with advanced skills in Big Data becaming "data steward" of their new data ecosystems, alongside the traditional statistical production processes. There is also evidence of the refluences that this data-ecosystem has on the labor market: changes in educational and learning environments  to adapt real-time traning programs for the future workplace expectationsm and to help people stay employable. Theoretical elements on the context of the Big-data licteracy, are based on interdisciplinary skills and competences to collaborate with people engaged in Big Data (not only data scientist but also statisticians, mathematicians, machine learning experts, ect.). Beyond the availability of massive raw data and the intention to understand and use them, there is potential for the implementation of policies to resolve the problems associated with the new dimension of digital divide.

Click [here]() to view the abstract.

## An overview of Tourism Statistical Literacy
***
#### *Yasir Jehan, Giuseppina Lo Mascolo and Stefano De Cantis*

<br>

**Abstract:** Tourism Statistics Literacy encompasses the ability to comprehend, analyse, and apply statistical data relevant to the tourism industry. This skill is crucial for stakeholders, including government bodies, businesses, and researchers, seeking to harness the vast potential of tourism. It involves interpreting key indicators such as tourist arrivals, accommodation occupancy rates, and economic contributions. Proficient tourism statistics literacy empowers decision-makers to formulate effective strategies, allocate resources efficiently, and respond to evolving market dynamics.  With accurate data interpretation, tourism statistics literacy becomes a cornerstone for fostering resilience, innovation, and optimal management within the complex tourism ecosystem.

Click [here]() to view the abstract.

## Scalable bootstrap inference via averaged Robbins-Monro approximations
***
#### *Giuseppe Alfonzetti and Ruggero Bellio*

<br>

**Abstract:** Bootstrap procedures are well-known for providing a straightforward approach to assess the uncertainty around quantities of interest in statistical models. However, with the rising prevalence of massive datasets in statistical problems, the computational cost of bootstrap methods can quickly become prohibitive in applied settings. To this end, this paper proposes the Averaged Robbins-Monro Bootstrap (ARM-B), a scalable tool for estimating parameters variability via multiple chains of Robbins-Monro updates. The simulation experiments show ARM-B to have comparable accuracy with bootstrap while significantly less computationally demanding.

Click [here]() to view the abstract.

## The impact of sustainability on Initial Coin Offering: advantages in trading
***
#### *Alessandro Bitetto and Paola Cerchiello*

<br>

**Abstract:** Initial Coin Offerings (ICOs) have emerged as a novel way of start-up funding based on blockchain technology and this paper aims at explaining the nexus between ICOs success and underpricing, i.e. when the price of the offered token is lower than the one traded in the market. In particular, we focus on the impact of the Environmental, Social and Governance (ESG) pillars onto the ICOs’ underpricing. Therefore, we built up a big and comprehensive dataset comprising ∼ 8000 ICOs spanning from 2015 through 2023, containing both technical and financial information. Moreover, we assessed an ESG score by means of advanced textual analysis performed over the whitepapers. The main results show that a higher ESG orienta- tion leads to less underpricing, especially in the early trading days.

Click [here]() to view the abstract.