---
pagetitle: "14:30 / 15:40 - Solicited 2 - C"
---


<br>


# Quantum neouromorphic approaches to data analysis and inference {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Organizer: Mauro Paternostro
### Chair: TBA

<br>

## Retrieving Past Quantum Features with Deep Hybrid classical-quantum Reservoir Computing
***
#### *Gian Luca Giorgi*

<br>

**Abstract:** Machine learning techniques have made remarkable progress in recent years, and the prospect of exploiting the principles of quantum physics opens up possibilities for improving classical learning methods. Rather than considering classical and quantum approaches as mutually exclusive options, there is a growing interest in integrating them into hybrid designs. In this context, we present a novel approach: deep hybrid classical-quantum reservoir computing for temporal processing of quantum states. This innovative framework allows the extraction of information about various aspects, such as entanglement or the purity of past input states, through a single-step measurement.

Our investigation shows that the hybrid configuration, combining two reservoirs, not only exploits the strengths of each component but also exceeds the performance of comparable non-hybrid alternatives. The proposed quantum layer design is based on continuous variables and focuses on the use of optical pulses, whose individual dynamics along a feedback loop define the reservoir computer.

Click [here]() to view the abstract.

## Quantum parameter estimation with quantum extreme learning machines
***
#### *Luca Innocenti, Salvatore Lorenzo, Ivan Palmisano, Francesco Albarelli, Alessandro Ferraro, Mauro Paternostro and Massimo G. Palma*

<br>

**Abstract:** Quantum extreme learning machines (QELMs) are computational paradigms that have recently attracted considerable interest thanks to their ease of implementation in many practical scenarios, and their potential for processing data encoded into input quantum states. We present an in-depth analysis of the potential of QELMs to estimate the properties of input states. In particular, we show that a full characterisation of the target properties achievable in this way is possible, and provide explicit conditions telling us when an observable is achievable in terms of the effective measurement corresponding to the dynamic of a given reservoir. We also prove a close analogy between the training process of QELMs and the reconstruction of the effective measurement characterising the given device. Finally, we show that the estimation framework of quantum shadow tomography fits naturally to analyse the performances of QELMs in the general case. Our analysis provides the theoretical foundations to better understand the potential and limitations of QELMs and reservoir computing, as well as explicit methods to apply these methods for practical experimental applications.

Click [here]() to view the abstract.

## Photonic memristor-based reservoir computing
***
#### *Iris Agresti*

<br>

**Abstract:** TBA


Click [here]() to view the abstract.