---
pagetitle: "12:10 / 13:20 - Solicited 1 - C"
---


<br>


# Young SIS {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Organizer: Marco Mingione
### Chair: TBA

<br>

## Merging data and historical information via optimal power prior selection in Bayesian models
***
#### *Roberto Macrì Demartino, Leonardo Egidi, Nicola Torelli and Ioannis Ntzoufras*

<br>

**Abstract:** In Bayesian analysis power prior distributions represent a key tool for integrating past information in clinical trials and similar studies: a crucial role is played by the weight parameter, which regulates the influence of the historical information with respect to the current sample. This parameter can be either fixed or random, and various strategies exist for its determination. We introduce a novel fully Bayesian method employing a calibrated Bayes factor to fine-tune the weight parameter’s initial distribution. This new method ensures that historical data is incorporated in a way that is proportional to its relevance and accuracy compared to current data. We apply our approach on some real melanoma clinical trial data, demonstrating its effectiveness in achieving a more balanced and accurate integration of historical information according to a modern machine learning perspective.

Click [here]() to view the abstract.

## Hierarchical Mixtures of Latent Trait Analyzers with concomitant variables
***
#### *Dalila Failli, Bruno Arpino, and Maria Francesca Marino*

<br>

**Abstract:** We extend the Mixture of Latent Trait Analyzers (MLTA) with concomitant variables in a multilevel framework to perform a hierarchical clustering of first- and second-level units. The use of Mixture of Latent Trait Analyzers allows us to cluster first-level units, while also accounting for the residual variability of items in the data matrix. Furthermore, a multilevel approach allows us to account for the hierarchical structure of the data. Last, the inclusion of concomitant variables enables us understanding how first-level units’ characteristics influence clustering formation.

Click [here]() to view the abstract.

## A Simultaneous Spectral Clustering for Three-Way Data
***
#### *Cinzia Di Nuzzo and Salvatore Ingrassia*

<br>

**Abstract:** We introduce a novel approach to spectral clustering for three-way data, which integrates simultaneous dimensionality reduction and clustering. While con- ventional spectral clustering methods focus on two-way data and treat dimensionality reduction and clustering separately, our proposed method extends to handle three-way data, capturing temporal repetition and multivariate interactions. This is the first method, which tackles this challenge purely through statistical techniques.

Click [here]() to view the abstract.