---
pagetitle: "14:30 / 15:40 - Solicited 2 - A"
---


<br>


# From Data Analysis to Data Science {#buttons .tabset .tabset-fade .tabset-pills}

<br>

### Organizer: Ndeye Niang
### Chair: TBA

<br>

## Optimal Scaling: New Insights Into an Old Problem
***
#### *Gilbert Saporta*

<br>

**Abstract:** Processing qualitative variables with a very large number of categories
in Machine Learning is an opportunity to revisit the theory of optimal scaling and its
applications.

Click [here]() to view the abstract.

## Linear Approximation For Multivariate Categorical Functional Data Analysis
***
#### *Cristian Preda and Quentin Grimonprez*

<br>

**Abstract:** Multivariate categorical functional data is considered in the framework of dimension reduction through principal component analysis. Each statistical unit is represented by a vector of categorical functions observed on some time interval [0,T]. The computational algorithm for the optimal encoding functions and principal components is then adapted through a linear approximation for the encoding functions. A numerical study using Markov simulated data illustrates the accuracy of such an approximation.

Click [here]() to view the abstract.

## An overview of multi-view clustering approaches
***
#### *Mohamed Nadif*

<br>

**Abstract:** Various clustering models and algorithms derived from different perspectives are valuable for analyzing data collected from various sources or represented in multiple ways, each offering a unique insight into the data; see for instance [3, 1]. Therefore, when dealing with such data, many approaches can be used, such as factorization techniques [5], probabilistic methods [6, 4, 7], or even deep neural networks [2]. The effectiveness of clustering algorithms typically depends on how the data is represented, emphasizing the importance of learning a suitable data representation. Consequently, integrating these two tasks is a common strategy for exploring this type of data. This presentation will explore, discuss, and demonstrate the range of approaches employed, ranging from traditional to cutting-edge methods.

Click [here]() to view the abstract.